"""add hits column to games

Revision ID: dae0d1bb6205
Revises: d763514fc00f
Create Date: 2026-09-17 10:47:50.981842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae0d1bb6205'
down_revision: Union[str, None] = 'd763514fc00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('hits', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'hits')
    # ### end Alembic commands ###
