"""add own shots and targeting state

Revision ID: ee7942a1e688
Revises: dae0d1bb6205
Create Date: 2026-09-25 11:05:09.775335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7942a1e688'
down_revision: Union[str, None] = 'dae0d1bb6205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('own_shots', sa.JSON(), nullable=False))
    op.add_column('games', sa.Column('pending_shot', sa.String(length=10), nullable=True))
    op.add_column('games', sa.Column('current_hits', sa.JSON(), nullable=False))
    op.add_column('games', sa.Column('target_queue', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'target_queue')
    op.drop_column('games', 'current_hits')
    op.drop_column('games', 'pending_shot')
    op.drop_column('games', 'own_shots')
    # ### end Alembic commands ###
